name: deploy-auth

on:
  workflow_dispatch: # Putting here is also fine!!
  push:
    branches: 
      - master 
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - run: cd auth && docker build -t rodolight/auth .
      - run: docker push rodolight/auth
