name: deploy-payments

on:
  workflow_dispatch: # Putting here is also fine!!
  push:
    branches: 
      - master 
    paths:
      - 'payments/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && docker build -t rodolight/payments .
      - run: 
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          $DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          $DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker push rodolight/payments
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment  payments-depl