name: tests-orders

on: 
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm install dotenv && npm install mongoose && npm run test:ci
